version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: stock_data_app_image
    container_name: stock_data_app_container
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1